name: many_radios
description: Many Radios.
publish_to: "none"

version: 0.3.0+3

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  path_provider: ^2.1.0
  http: ^0.13.5
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  x_responsive: ^0.2.0
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  url_launcher: ^6.1.14
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/radio.png
    - assets/images/notification.png

flutter_intl:
  enabled: true
