name: many_radios
description: Many Radios.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  audioplayers: ^5.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  x_responsive: ^0.2.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/radio.png

flutter_intl:
  enabled: true
